[package]
name = "qb_mutex"
version = "0.1.0"
authors = ["machine <machineswift@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
